docs:
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - '**/*.md'
          - all-globs-to-all-files:
              - '!frontend/**'
              - '!services/**'
              - '!.github/**'
              - '!scripts/**'
              - '!.gitignore'
              - '!.pre-commit-config.yaml'

internal:
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - .github/**
              - scripts/**
              - .gitignore
              - .pre-commit-config.yaml
          - all-globs-to-all-files:
              - '!./**/*.md'
              - '!frontend/**'
              - '!services/**'

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - frontend/**

user-service:
  - changed-files:
      - any-glob-to-any-file:
          - services/user-service/**

product-service:
  - changed-files:
      - any-glob-to-any-file:
          - services/product-service/**

order-service:
  - changed-files:
      - any-glob-to-any-file:
          - services/order-service/**
