// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
}

export type ItemPublic = {
  title: string
  description?: string | null
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
}

export type Message = {
  message: string
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type ItemsReadItemsData = {
  args: unknown
  kwargs: unknown
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  args: unknown
  kwargs: unknown
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  args: unknown
  itemId: string
  kwargs: unknown
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  args: unknown
  itemId: string
  kwargs: unknown
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  args: unknown
  itemId: string
  kwargs: unknown
}

export type ItemsDeleteItemResponse = Message

export type UtilsHealthCheckResponse = boolean
