name: Generate Client

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  generate-client:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service, product-service, order-service]

    steps:
      # Checkout the repo
      - uses: actions/checkout@v5

      # For PRs from the same repo
      - uses: actions/checkout@v5
        if: ( github.event_name != 'pull_request' || github.secret_source == 'Actions' )
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.FULL_STACK_FASTAPI_TEMPLATE_REPO_TOKEN }}

      - uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.4.15"
          enable-cache: true

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Install service dependencies
        run: uv sync
        working-directory: services/${{ matrix.service }}

      - name: Generate client
        run: uv run bash scripts/generate-client.sh
        working-directory: services/${{ matrix.service }}
        env:
          VIRTUAL_ENV: services/${{ matrix.service }}/.venv
          SECRET_KEY: just-for-generating-client
          POSTGRES_PASSWORD: just-for-generating-client
          FIRST_SUPERUSER_PASSWORD: just-for-generating-client

      - name: Add changes to git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git add frontend/src/client

      # Push changes for same-repo PRs
      - name: Push changes
        if: ( github.event_name != 'pull_request' || github.secret_source == 'Actions' )
        run: |
          git diff --staged --quiet || git commit -m "✨ Autogenerate frontend client for ${{ matrix.service }}"
          git push

      # Check changes for fork PRs
      - name: Check changes
        if: ( github.event_name == 'pull_request' && github.secret_source != 'Actions' )
        run: |
          git diff --staged --quiet || (echo "Changes detected in generated client for ${{ matrix.service }}, run scripts/generate-client.sh inside services/${{ matrix.service }} and commit the changes" && exit 1)
